name: GNU/Linux build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev libglu1-mesa-dev freeglut3-dev

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/android_demo1 data

    - name: build demo
      run: |
        make

    - uses: actions/upload-artifact@v4
      with:
        name: demo-gnulinux
        path: |
          data/
          sdr/
          demo
