name: Win32 build (MSVC)


on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: prepare environment
      uses: microsoft/setup-msbuild@v1.0.2

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/android_demo1 data

    - name: build demo
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild -m -p:Configuration=Release -t:andemo
        copy x64\Release\demo.exe demo.exe

    - uses: actions/upload-artifact@v3
      with:
        name: demo-win32
        path: |
          data/
          sdr/
          demo.exe
